---
baseurl: "http://caramelomartins.github.io/"
title: "caramelomartins' ~/"

permalinks:
    fixed: ":title/"
    blog: "blog/:slug/"

params:
    dateform: "Jan 2, 2006"
    dateformfull: "Mon Jan 2 2006 15:04:05 MST"

    initials: "HM"
    author: "Hugo Martins"

    github: "https://github.com/caramelomartins"
...
