baseurl: "https://hugomartins.io/"

title: "Hugo Martins"

contentdir: "content"
layoutdir: "layout"
publishdir: "public"

theme: candy
builddrafts: false

pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: solarized-dark

menu:
  main:
    - name: "Essays"
      identifier: "Essays"
      url: "/essays/"
      weight: -110

    - name: "Series"
      identifier: "Series"
      url: "/series/"
      weight: -100

    - name: "About"
      identifier: "about"
      url: "/about/"
      weight: -90

    - name: "Code"
      identifier: "code"
      url: "/code/"
      weight: -80

    - name: "Research"
      identifier: "research"
      url: "/research/"
      weight: -70

enableRobotsTXT: true
canonifyURLs: true

params:
  author: "Hugo Martins"
  plausible: hugomartins.io
  description: "Writings on technology, engineering and anything in between by Hugo Martins."

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
