baseurl: "http://hugomartins.io/"
builddrafts: false
contentdir: "content"
layoutdir: "layout"
publishdir: "public"
title: "caramelomartins' ~/"
author: "Hugo Martins"
theme: hugo-flex

permalinks:
  fixed: ":title/"
  blog: "blog/:slug/"

menu:
  nav:
    - Name: "Blog"
      Weight: -120
      Identifier: "blog"
      URL: "/blog/"

    - Name: "About"
      Weight: -110
      Identifier: "about"
      URL: "/about/"

    - Name: "Code"
      Weight: -100
      Identifier: "code"
      URL: "/code/"

    - Name: "Research"
      Weight: -90
      Identifier: "research"
      URL: "/research/"

params:
  dateform: "Jan 2, 2006"
  dateformfull: "Mon Jan 2 2006 15:04:05 MST"

  initials: "HM"
  author: "Hugo Martins"
  selfintro: "Thoughts on programming, engineering and curly brackets."

  highlightjs: true
  lang: "en"

  github: "https://github.com/caramelomartins"
  linkedin: "https://www.linkedin.com/in/hugofcsmartins"

  # Hugo Flex Specific
  color: darkslategray  # Any color in CSS syntax
  width: 42rem  # Any length in CSS syntax
  footer: Except where otherwise noted, content on this site is licensed under
    a <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.