baseurl: "http://hugomartins.io/"

title: "Hugo Martins"
description: "Writings on technology and engineering by Hugo Martins"
author: "Hugo Martins"

contentdir: "content"
layoutdir: "layout"
publishdir: "public"

theme: candy
builddrafts: false

menu:
  main:
    - name: "Essays"
      identifier: "Essays"
      url: "/essays/"
      weight: -110

    - name: "About"
      identifier: "about"
      url: "/about/"
      weight: -100

    - name: "Code"
      identifier: "code"
      url: "/code/"
      weight: -90

    - name: "Research"
      identifier: "research"
      url: "/research/"
      weight: -80

